# 19 March class 21

working on excel datasets available in folder class 21 march 19

numbers - numerical data

text - categorical data

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [5]:
# to read datasets from csv(comma separated value) files
store = pd.read_csv(r'D:\My data science career\python\class 21 march 19\19th, 20th - Pandas\19th, 20th - Pandas\Sample - Superstore_Orders.csv')
store

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [6]:
id(store)

1813373666272

In [7]:
len(store)
# no. of rows except attributes columns

10194

In [8]:
# shape - it shows rows and columns number
store.shape

(10194, 19)

In [9]:
# to show the columns name
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [10]:
# number of columns
len(store.columns)

19

In [11]:
# is there any null value stored in datasets
store.isnull()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
# count of any null (missing) value stored in datasets
store.isnull().sum()

Category          0
City              0
Country/Region    0
Customer Name     0
Manufacturer      0
Order Date        0
Order ID          0
Postal Code       0
Product Name      0
Region            0
Segment           0
Ship Date         0
Ship Mode         0
State/Province    0
Sub-Category      0
Discount          0
Profit            0
Quantity          0
Sales             0
dtype: int64

In [13]:
# slicing in dataframe
store[:]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [14]:
store[0:10] # show rows from 1 to 9 -> to get first 10 records in dataset

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
6,Office Supplies,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Handheld Barrel Pencil Sharpener,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.0,1.4796,2,5.480
7,Office Supplies,Athens,United States,Jack O'Briant,Dixon,06-01-2020,US-2020-106054,30605,"Dixon Prang Watercolor Pencils, 10-Color Set w...",South,Corporate,07-01-2020,First Class,Georgia,Art,0.0,5.2398,3,12.780
8,Office Supplies,Henderson,United States,Maria Etezadi,Ibico,06-01-2020,US-2020-167199,42420,Ibico Hi-Tech Manual Binding System,South,Home Office,10-01-2020,Standard Class,Kentucky,Binders,0.0,274.4910,2,609.980
9,Office Supplies,Henderson,United States,Maria Etezadi,Alliance,06-01-2020,US-2020-167199,42420,"Alliance Super-Size Bands, Assorted Sizes",South,Home Office,10-01-2020,Standard Class,Kentucky,Fasteners,0.0,0.3112,4,31.120

In [15]:
store[0:20:5]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
10,Office Supplies,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth 25% Cotton Granite Paper & Envelopes,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
15,Office Supplies,Huntsville,United States,Vivek Sundaresam,Acco,07-01-2020,US-2020-105417,77340,Acco Four Pocket Poly Ring Binder with Label H...,Central,Consumer,12-01-2020,Standard Class,Texas,Binders,0.8,-18.2525,7,10.430

In [16]:
# by default it gives top 5 rows (record)
store.head()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536

In [17]:
# gives top 3 rows (record)
store.head(3)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784

In [18]:
# by default it gives bottom 5 rows (record)
store.tail()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [19]:
# gives bottom 3 rows (record)
store.tail(3)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [20]:
# is there any null value stored in datasets
store.isnull()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
# is there any null value stored in datasets
#store.isnull()
# another way to write the above code
store.isna()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Introduction of statistical concept in pandas :-

In [23]:
# describe refers to descriptive statistics -> displays numerical data statistics 
store.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

count -> shows total number of rows

mean -> average of the numeric data

min -> minimum value in dataset

max -> maximum value in dataset

std -> standard deviation 

percentiles(aka quartile):-

25% (lower quartile) -> 25% data below this data

50% (medium quartile aka mean/meadian) ->

75% (upper quartile) ->

# 20 March class 22

In [51]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [67]:
store['Category']
# to display data of column Category

0        Office Supplies
1        Office Supplies
2        Office Supplies
3        Office Supplies
4        Office Supplies
              ...
10189    Office Supplies
10190    Office Supplies
10191    Office Supplies
10192         Technology
10193    Office Supplies
Name: Category, Length: 10194, dtype: object

In [69]:
store[['Category', 'City']]
# to print data of two attributes

              Category           City
0      Office Supplies        Houston
1      Office Supplies     Naperville
2      Office Supplies     Naperville
3      Office Supplies     Naperville
4      Office Supplies   Philadelphia
...                ...            ...
10189  Office Supplies  New York City
10190  Office Supplies      Fairfield
10191  Office Supplies       Loveland
10192       Technology  New York City
10193  Office Supplies  Charlottetown

[10194 rows x 2 columns]

In [71]:
store[['Category','City','Customer Name']]
# display data of three columns

              Category           City      Customer Name
0      Office Supplies        Houston      Darren Powers
1      Office Supplies     Naperville      Phillina Ober
2      Office Supplies     Naperville      Phillina Ober
3      Office Supplies     Naperville      Phillina Ober
4      Office Supplies   Philadelphia         Mick Brown
...                ...            ...                ...
10189  Office Supplies  New York City  Patrick O'Donnell
10190  Office Supplies      Fairfield         Erica Bern
10191  Office Supplies       Loveland      Jill Matthias
10192       Technology  New York City  Patrick O'Donnell
10193  Office Supplies  Charlottetown        Harry Olson

[10194 rows x 3 columns]

In [ ]:
# divide the dataset into categorical & numerical

In [75]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [87]:
store_cat = store[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category']]
store_cat

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders

In [93]:
store_cat.info()
# information of the dataframes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
dtypes: object(15)
memory usage: 1.2+ MB

In [91]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
 15  Discount        10194 non-null  float64
 16  Profit          10194 non-null  float64
 17  Quantity        10194 non-null  int64
 18  Sales           10194 non-null  float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [99]:
len(store.columns)
# memory usage 1.5 MB

19

In [101]:
len(store_cat.columns)
# memory usage 1.2 MB

15

the above memory allocation is done by constructor.
in Python __INT__ constructor is used to do this memory allocation.

In [107]:
store_num = store[['Discount', 'Profit', 'Quantity', 'Sales']]
store_num
# to store numeral data attributes

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [105]:
store_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Discount  10194 non-null  float64
 1   Profit    10194 non-null  float64
 2   Quantity  10194 non-null  int64
 3   Sales     10194 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 318.7 KB

In [117]:
len(store.columns)

19

In [115]:
len(store_cat.columns)

15

In [113]:
len(store_num.columns)

4

In [119]:
store_cat.describe()
# to decribe categorical data

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,3,542,2,800,183,1242,5111,655,1849,4,3,1338,4,59,17
top,Office Supplies,New York City,United States,William Brown,Other,05-09-2022,US-2023-100111,10035,Staples,West,Consumer,16-12-2021,Standard Class,California,Binders
freq,6128,915,9994,41,1940,38,14,263,50,3253,5281,38,6120,2001,1548

In [121]:
store_num.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

# BASIC PANDAS INTRODUCTION IS COMPLETED

# PROJECT country GDP analysis

check jupyter notebook